# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

beta_update_FGMRM <- function(X, y, gamma_mat, pi, sigma, V, lambda, penalty) {
    .Call(`_regMR_beta_update_FGMRM`, X, y, gamma_mat, pi, sigma, V, lambda, penalty)
}

sigma_update <- function(X, y, gamma_mat, beta, N) {
    .Call(`_regMR_sigma_update`, X, y, gamma_mat, beta, N)
}

sigma_update_pen <- function(X, y, iqr_var, n, gamma_mat, beta, N) {
    .Call(`_regMR_sigma_update_pen`, X, y, iqr_var, n, gamma_mat, beta, N)
}

lambda_max_compute_FGMRM <- function(X, y, gamma_mat, pi, sigma) {
    .Call(`_regMR_lambda_max_compute_FGMRM`, X, y, gamma_mat, pi, sigma)
}

beta_update_FPMRM <- function(x, y, z_mat, beta_old, V, lambda, penalty = FALSE, max_iter = 500L, tol = 1e-8, verbose = FALSE) {
    .Call(`_regMR_beta_update_FPMRM`, x, y, z_mat, beta_old, V, lambda, penalty, max_iter, tol, verbose)
}

sgl_penalty_FPMRM <- function(lambda, alpha, beta, G) {
    .Call(`_regMR_sgl_penalty_FPMRM`, lambda, alpha, beta, G)
}

