# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

beta_update <- function(X, y, gamma_mat, sigma, V, lambda, penalty) {
    .Call(`_regMR_beta_update`, X, y, gamma_mat, sigma, V, lambda, penalty)
}

sigma_update <- function(X, y, gamma_mat, beta, N) {
    .Call(`_regMR_sigma_update`, X, y, gamma_mat, beta, N)
}

sigma_update_pen <- function(X, y, iqr_var, n, gamma_mat, beta, N) {
    .Call(`_regMR_sigma_update_pen`, X, y, iqr_var, n, gamma_mat, beta, N)
}

lambda_max_compute <- function(X, y, gamma_mat) {
    .Call(`_regMR_lambda_max_compute`, X, y, gamma_mat)
}

